In [2]:
import pandas as pd

In [3]:
sample_df = pd.read_csv('../data/sample_submission.csv')
print(sample_df.shape)
sample_df[:2]

(93800, 2)

       id  Depression
0  140700           0
1  140701           0

In [4]:
test_df = pd.read_csv('../data/test.csv')
print(test_df.shape)
test_df[:2]
# (93800, 19)

(93800, 19)

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No

In [5]:
train_df = pd.read_csv('../data/train.csv')
print(train_df.shape)
train_df[:2]
# (140700, 20)

(140700, 20)

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1

In [9]:
pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.12.0-py2.py3-none-any.whl.metadata (20 kB)
Collecting scipy<1.14,>=1.4.1 (from ydata-profiling)
  Downloading scipy-1.13.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<3.10,>=3.5 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (3.9.0)
Requirement already satisfied: pydantic>=2 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (2.9.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (6.0.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (3.1.4)
Collecting visions<0.7.7,>=0.7.5 (from visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling)
  Downloading visions-0.7.6-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (4.66.5)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (1.12)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Downloading statsmodels-0.14.4-cp312-cp312-win_amd64.whl.metadata (9.5 kB)
Collecting typeguard<5,>=3 (from ydata-profiling)
  Downloading typeguard-4.4.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: imagehash==4.3.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling) (4.3.1)
Collecting wordcloud>=1.9.3 (from ydata-profiling)
  Downloading wordcloud-1.9.4-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.8.1-py3-none-any.whl.metadata (15 kB)
Collecting numba<1,>=0.56.0 (from ydata-profiling)
  Downloading numba-0.60.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: PyWavelets in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (1.7.0)
Requirement already satisfied: pillow in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (10.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (24.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba<1,>=0.56.0->ydata-profiling)
  Downloading llvmlite-0.43.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: joblib>=0.14.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from pydantic>=2->ydata-profiling) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from pydantic>=2->ydata-profiling) (4.12.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2024.6.2)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: colorama in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (23.2.0)
Requirement already satisfied: networkx>=2.4 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (3.4.1)
Requirement already satisfied: six>=1.5 in c:\users\m.s.i\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib<3.10,>=3.5->ydata-profiling) (1.16.0)
Downloading ydata_profiling-4.12.0-py2.py3-none-any.whl (390 kB)
Downloading dacite-1.8.1-py3-none-any.whl (14 kB)
Downloading numba-0.60.0-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 275.1 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.7 MB 275.1 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.7 MB 275.1 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.7 MB 275.1 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.7 MB 284.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.7 MB 284.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.7 MB 284.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.7 MB 284.3 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.7 MB 284.3 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.7 MB 267.8 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.7 MB 267.8 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.7 MB 267.8 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.7 MB 267.8 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.7 MB 267.8 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.7 MB 267.8 kB/s eta 0:00:07
   ------------------- -------------------- 1.3/2.7 MB 262.1 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.7 MB 262.1 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.7 MB 262.1 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.7 MB 262.1 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.7 MB 262.1 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.7 MB 262.1 kB/s eta 0:00:06
   ----------------------- ---------------- 1.6/2.7 MB 248.9 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.7 MB 248.9 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.7 MB 248.9 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.7 MB 248.9 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.7 MB 248.9 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.7 MB 248.9 kB/s eta 0:00:05
   --------------------------- ------------ 1.8/2.7 MB 243.1 kB/s eta 0:00:04
   --------------------------- ------------ 1.8/2.7 MB 243.1 kB/s eta 0:00:04
   --------------------------- ------------ 1.8/2.7 MB 243.1 kB/s eta 0:00:04
   --------------------------- ------------ 1.8/2.7 MB 243.1 kB/s eta 0:00:04
   --------------------------- ------------ 1.8/2.7 MB 243.1 kB/s eta 0:00:04
   ------------------------------ --------- 2.1/2.7 MB 243.1 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.7 MB 243.1 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.7 MB 243.1 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.7 MB 243.1 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.7 MB 243.1 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.7 MB 243.1 kB/s eta 0:00:03
   ---------------------------------- ----- 2.4/2.7 MB 240.1 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.7 MB 240.1 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.7 MB 240.1 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.7 MB 249.2 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 249.2 kB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 248.4 kB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-win_amd64.whl (45.9 MB)
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/45.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/45.9 MB 192.9 kB/s eta 0:03:56
   ---------------------------------------- 0.5/45.9 MB 192.9 kB/s eta 0:03:56
   ---------------------------------------- 0.5/45.9 MB 192.9 kB/s eta 0:03:56
   ---------------------------------------- 0.5/45.9 MB 192.9 kB/s eta 0:03:56
   ---------------------------------------- 0.5/45.9 MB 192.9 kB/s eta 0:03:56
   ---------------------------------------- 0.5/45.9 MB 192.9 kB/s eta 0:03:56
   ---------------------------------------- 0.5/45.9 MB 192.9 kB/s eta 0:03:56
    --------------------------------------- 0.8/45.9 MB 188.5 kB/s eta 0:04:00
    --------------------------------------- 0.8/45.9 MB 188.5 kB/s eta 0:04:00
    --------------------------------------- 0.8/45.9 MB 188.5 kB/s eta 0:04:00
    --------------------------------------- 0.8/45.9 MB 188.5 kB/s eta 0:04:00
    --------------------------------------- 0.8/45.9 MB 188.5 kB/s eta 0:04:00
    --------------------------------------- 0.8/45.9 MB 188.5 kB/s eta 0:04:00
    --------------------------------------- 0.8/45.9 MB 188.5 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
    --------------------------------------- 1.0/45.9 MB 187.1 kB/s eta 0:04:00
   - -------------------------------------- 1.3/45.9 MB 180.9 kB/s eta 0:04:07
   - -------------------------------------- 1.3/45.9 MB 180.9 kB/s eta 0:04:07
   - -------------------------------------- 1.3/45.9 MB 180.9 kB/s eta 0:04:07
   - -------------------------------------- 1.3/45.9 MB 180.9 kB/s eta 0:04:07
   - -------------------------------------- 1.3/45.9 MB 180.9 kB/s eta 0:04:07
   - -------------------------------------- 1.3/45.9 MB 180.9 kB/s eta 0:04:07
   - -------------------------------------- 1.3/45.9 MB 180.9 kB/s eta 0:04:07
   - -------------------------------------- 1.6/45.9 MB 181.2 kB/s eta 0:04:05
   - -------------------------------------- 1.6/45.9 MB 181.2 kB/s eta 0:04:05
   - -------------------------------------- 1.6/45.9 MB 181.2 kB/s eta 0:04:05
   - -------------------------------------- 1.6/45.9 MB 181.2 kB/s eta 0:04:05
   - -------------------------------------- 1.6/45.9 MB 181.2 kB/s eta 0:04:05
   - -------------------------------------- 1.6/45.9 MB 181.2 kB/s eta 0:04:05
   - -------------------------------------- 1.6/45.9 MB 181.2 kB/s eta 0:04:05
   - -------------------------------------- 1.8/45.9 MB 178.5 kB/s eta 0:04:07
   - -------------------------------------- 1.8/45.9 MB 178.5 kB/s eta 0:04:07
   - -------------------------------------- 1.8/45.9 MB 178.5 kB/s eta 0:04:07
   - -------------------------------------- 1.8/45.9 MB 178.5 kB/s eta 0:04:07
   - -------------------------------------- 1.8/45.9 MB 178.5 kB/s eta 0:04:07
   - -------------------------------------- 1.8/45.9 MB 178.5 kB/s eta 0:04:07
   - -------------------------------------- 1.8/45.9 MB 178.5 kB/s eta 0:04:07
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   - -------------------------------------- 2.1/45.9 MB 179.0 kB/s eta 0:04:05
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.4/45.9 MB 177.5 kB/s eta 0:04:06
   -- ------------------------------------- 2.6/45.9 MB 164.5 kB/s eta 0:04:24
   -- ------------------------------------- 2.6/45.9 MB 164.5 kB/s eta 0:04:24
   -- ------------------------------------- 2.6/45.9 MB 164.5 kB/s eta 0:04:24
   -- ------------------------------------- 2.6/45.9 MB 164.5 kB/s eta 0:04:24
   -- ------------------------------------- 2.6/45.9 MB 164.5 kB/s eta 0:04:24
   -- ------------------------------------- 2.6/45.9 MB 164.5 kB/s eta 0:04:24
   -- ------------------------------------- 2.6/45.9 MB 164.5 kB/s eta 0:04:24
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 2.9/45.9 MB 165.8 kB/s eta 0:04:20
   -- ------------------------------------- 3.1/45.9 MB 160.8 kB/s eta 0:04:27
   -- ------------------------------------- 3.1/45.9 MB 160.8 kB/s eta 0:04:27
   -- ------------------------------------- 3.1/45.9 MB 160.8 kB/s eta 0:04:27
   -- ------------------------------------- 3.1/45.9 MB 160.8 kB/s eta 0:04:27
   -- ------------------------------------- 3.1/45.9 MB 160.8 kB/s eta 0:04:27
   -- ------------------------------------- 3.1/45.9 MB 160.8 kB/s eta 0:04:27
   -- ------------------------------------- 3.1/45.9 MB 160.8 kB/s eta 0:04:27

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.7.6 which is incompatible.
scikit-learn 1.5.2 requires joblib>=1.2.0, but you have joblib 1.1.1 which is incompatible.

In [11]:
from ydata_profiling import ProfileReport

profile = ProfileReport(train_df, title="Pandas Profiling Report")
profile.to_file("../mental_health_pandas_profiling.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]